name: datepicker
version: 0.1.7
author: Jo√£o Furtado<jrofurtado@gmail.com>
description: Date Input using a Date Picker
homepage: https://github.com/jrofurtado/datepicker
dependencies:
  browser: any
  intl: any
  web_ui: any
